### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by penpenpng** [penpenpng/skylight#5]
List of things that might be implemented.

- [ ] Notification badge 
- [ ] Improve notification tab tile UI
- [ ] Optional auto refresh
- [x] Display images
- [x] Display quoted note
- [ ] Show users reposting or voting
- [ ] Post detail page
- [ ] Show reply parent in timeline
- [ ] Add route /profile/:handle/follows, followers, posts
- [ ] Update profile
- [ ] Post image
- [x] Delete post
- [ ] Toast feedback
- [x] LISENCE
- [x] Post note including URL
- [x] Post reply
- [x] Display users' header image
- [x] Link to user profile
- [x] Notification tab
- [ ] Infinite scrolling
- [ ] Position-fixed input UI
- [ ] Keyboard shortcut to focus input UI
- [ ] PWA support
- [ ] Fix layout issue
- [x] Performance improvement
